# 如果需要測試，請在終端機下docker-compose -f docker-compose.yml up 
version: '3'
services:
  db:
      image: webserver-mariadb:latest
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
      restart: always
      container_name: tku-mariadb
      ports:
        - 192.168.1.102:3306:3306
      environment:
        TZ: Asia/Taipei
        encoding: utf8
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: marksun
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: rbase
      volumes:
        - ../mysql:/var/lib/mysql:rw
    
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: tku-phpmyadmin
      ports: 
        - 8080:80
      depends_on:
        - db
      environment:
        TZ: Asia/Taipei
        encoding: utf8
        PMA_USER: root
        PMA_PASSWORD: 123456








